import { callGroq, GROQ_CLASSIFIER_MODEL, GROQ_PRIMARY_MODEL, type GroqMessage } from './groq'

// PRD v1.6's "candidate generation + ranking" upgrade: instead of one
// gpt-oss-120b completion, generate three at different temperatures (same
// model, same context/directive — never a different model), have a fast
// gpt-oss-20b ranker call pick the best one, then run the winner through
// the therapy-speak filter before it ever reaches the client.

export const CANDIDATE_TEMPERATURES = [0.7, 0.85, 1.0] as const
export const CANDIDATE_LETTERS = ['A', 'B', 'C'] as const
export type CandidateLetter = (typeof CANDIDATE_LETTERS)[number]

export type CandidateSet = Record<CandidateLetter, string>

// Generates the 3 candidate replies in parallel — same model
// (GROQ_PRIMARY_MODEL), same messages/context/directive, differing only by
// temperature for natural variation.
export async function generateCandidates(
  apiKey: string,
  messages: GroqMessage[],
  jsonMode: boolean,
  maxTokens: number,
): Promise<CandidateSet> {
  const [a, b, c] = await Promise.all(
    CANDIDATE_TEMPERATURES.map((temperature) =>
      callGroq(apiKey, { model: GROQ_PRIMARY_MODEL, jsonMode, maxTokens, temperature, messages }),
    ),
  )
  return { A: a, B: b, C: c }
}

interface ParsedMultiMessage {
  text: string
  delay: number
}

// Tolerant parse of the multi-message JSON shape the main model is asked
// for when analysis.multi_message is true — accepts a bare array instead
// of {"messages": [...]}, or a "message"/"content" key instead of "text",
// and falls back to treating the whole raw string as one message if the
// JSON doesn't parse at all. Shared by the client-facing response shape
// and by extractPlainText() below (for scoring/ranking).
export function parseMultiMessageJson(raw: string): ParsedMultiMessage[] {
  let parsedMessages: ParsedMultiMessage[] = []
  try {
    const parsed: unknown = JSON.parse(raw)
    const list: unknown = Array.isArray(parsed) ? parsed : (parsed as { messages?: unknown })?.messages
    if (Array.isArray(list)) {
      parsedMessages = list
        .map((m) => {
          if (typeof m === 'string') return { text: m, delay: undefined as unknown }
          if (!m || typeof m !== 'object') return null
          const obj = m as Record<string, unknown>
          const text = obj.text ?? obj.message ?? obj.content
          return typeof text === 'string' ? { text, delay: obj.delay } : null
        })
        .filter((m): m is { text: string; delay: unknown } => !!m && m.text.trim().length > 0)
        .slice(0, 3)
        .map((m, i) => ({
          text: m.text.trim(),
          delay: typeof m.delay === 'number' && Number.isFinite(m.delay) ? m.delay : i * 800,
        }))
    }
  } catch {
    // Malformed multi-message JSON — fall back to the raw text as one
    // message rather than failing the whole request over response shape.
  }
  if (parsedMessages.length === 0) {
    parsedMessages = [{ text: raw.trim(), delay: 0 }]
  }
  return parsedMessages
}

// Plain-text form of a candidate, used for ranking and therapy-speak
// scoring — for a multi-message candidate this is its bubbles joined,
// not the raw JSON (scoring raw JSON would miss "starts with" checks and
// double-count phrases inside quoted strings).
export function extractPlainText(raw: string, multiMessage: boolean): string {
  if (!multiMessage) return raw.trim()
  return parseMultiMessageJson(raw)
    .map((m) => m.text)
    .join('\n\n')
}

const RANKER_PROMPT = `You are a fast quality ranker for Your Reflection's response candidates.
You are given the conversation directive (the move, length, question
budget, and appraisal the response should match) and three candidate
replies — A, B, and C — generated by the same model at different
temperatures. Pick the single best one.

Score each candidate on:
- Naturalness: sounds like a real person texting, not an assistant.
- Emotional fit to the appraisal: matches what's actually at stake, not just the emotion label.
- Therapy-speak penalty: penalize "I hear you", "it sounds like", "that must be", "your feelings are valid", and similar clinical/performed-empathy phrasing.
- Question penalty: if the directive's question budget is 0, heavily penalize any candidate that asks a question anyway.
- Contextual specificity: responds to the specific thing said, not a generic reply that could answer anything.

Respond with ONLY JSON, no other text: {"winner": "A" | "B" | "C", "reason": "one line"}`

export interface RankerResult {
  winner: CandidateLetter
  reason: string
}

// Fails open to candidate A rather than blocking the response on a
// ranker failure — matches analyzeConversation's own fail-open pattern.
export async function rankCandidates(
  apiKey: string,
  directive: string,
  candidateTexts: CandidateSet,
): Promise<RankerResult> {
  try {
    const raw = await callGroq(apiKey, {
      model: GROQ_CLASSIFIER_MODEL,
      jsonMode: true,
      temperature: 0,
      maxTokens: 120,
      messages: [
        { role: 'system', content: RANKER_PROMPT },
        {
          role: 'user',
          content: `${directive}\n\n[CANDIDATE A]\n${candidateTexts.A}\n\n[CANDIDATE B]\n${candidateTexts.B}\n\n[CANDIDATE C]\n${candidateTexts.C}`,
        },
      ],
    })
    const parsed = JSON.parse(raw) as { winner?: unknown; reason?: unknown }
    const winner: CandidateLetter = CANDIDATE_LETTERS.includes(parsed.winner as CandidateLetter)
      ? (parsed.winner as CandidateLetter)
      : 'A'
    const reason =
      typeof parsed.reason === 'string' && parsed.reason.trim() ? parsed.reason.trim() : 'ranker gave no reason'
    return { winner, reason }
  } catch (err) {
    console.error('response ranker failed, defaulting to candidate A', err)
    return { winner: 'A', reason: 'fallback: ranker call failed' }
  }
}

// PRD v1.6's therapy-speak post-filter: scores generated
// performed-empathy boilerplate so it can be caught even when it slips
// past the ranker. THERAPY_SPEAK_THRESHOLD (>= 4) is "too therapeutic" —
// pass over it for the next-best candidate instead of sending it.
export const THERAPY_SPEAK_THRESHOLD = 4

const THERAPY_SPEAK_RULES: { test: (lower: string) => boolean; points: number }[] = [
  { test: (t) => t.trimStart().startsWith('i hear'), points: 3 },
  { test: (t) => t.includes('it sounds like'), points: 2 },
  { test: (t) => t.includes('it feels like you'), points: 2 },
  { test: (t) => t.includes("i'm noticing") || t.includes('i am noticing'), points: 2 },
  { test: (t) => t.includes('sitting with'), points: 1 },
  { test: (t) => t.includes("what's coming up for you") || t.includes('what is coming up for you'), points: 2 },
  { test: (t) => t.includes('your feelings are valid'), points: 3 },
  { test: (t) => t.includes('take some time'), points: 1 },
  { test: (t) => t.includes('that must be'), points: 1 },
]

export function scoreTherapySpeak(text: string): number {
  const lower = text.toLowerCase()
  return THERAPY_SPEAK_RULES.reduce((score, rule) => score + (rule.test(lower) ? rule.points : 0), 0)
}
